name: Build

on:
  pull_request:
  push:
    branches: [main, betatest]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the app
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v3

        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          retetion-days: 30

  download-and-send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: my-artifact

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install curl
        run: sudo apt install curl

      - name: Send to tg
        run: curl -F "document=@my-artifact/app" -F "chat_id=${{ secrets.TELEGRAM_TO }}" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
