name: Build

on:
  pull_request:
  push:
    branches: [main, betatest]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the app
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v3

        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          retetion-days: 30

      - name: Send artifact
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: gradlew

  download and send:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Display structure of downloaded files
        run: ls -R