name: Build

on:
  pull_request:
  push:
    branches: [main, betatest]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the app
        run: ./gradlew assemble

      - name: upload artifact
        uses: actions/upload-artifact@v3

        with:
          name: app.apk
          path: app
          retetion-days: 30
